service: "cmr-${self:custom.cmrStacName}-api"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  role: cmrStacRole
  stage: dev
  deploymentBucket: cmr-maap-cmr-stac-api-ua-serverlessdeploymentbuck-1vmumzd6d073v
custom:
  cmrStacName: ${opt:cmr-stac-name}
  cmrStacRelativeRootUrl: ${opt:cmr-stac-relative-root-url, '/stac'}
  docsBucket: cmr-stac-static-bucket-dev
  assets:
    targets:
      - bucket:
          Ref: cmrStacDocsBucket
        empty: true
        prefix: docs
        files:
          - source: ./docs/
            globs: '**/index.html'

functions:
  search-api:
    name: cmr-${self:custom.cmrStacName}-dev
    handler: lib/application.handler
    timeout: 6
    logSubscription: true
    environment:
      CMR_SEARCH_HOST: ${opt:cmr-search-host, 'cmr.earthdata.nasa.gov/search'}
      CMR_PROVIDER_HOST: ${opt:cmr-provider-host, 'cmr.earthdata.nasa.gov/ingest/providers'}
      CMR_SEARCH_PROTOCOL: ${opt:cmr-search-protocol, 'https'}
      CMR_STAC_RELATIVE_ROOT_URL: ${self:custom.cmrStacRelativeRootUrl}
      BROWSE_PATH: year/month/day
      LOG_DISABLED: false
      LOG_LEVEL: info
      STAC_VERSION: 1.0.0-rc.4

resources:
  Resources:
    cmrStacRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: cmrStacRole-${self:custom.cmrStacName}-dev
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
    cmrStacDocsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.docsBucket}

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-log-subscription
  - serverless-s3-deploy
